<?php
/** V7.12 Live Management Dashboard. Adaptive WP data layer; preserves existing business logic. */
defined('ABSPATH') || exit;
if(!class_exists('ACLM_V712_Live_Management_Dashboard')){
final class ACLM_V712_Live_Management_Dashboard {
 public static function init(){add_shortcode('arkana_live_management_dashboard',array(__CLASS__,'shortcode'));}
 private static function allowed(){return current_user_can('manage_options')||current_user_can('ac_managing_partner')||current_user_can('ac_partner')||current_user_can('ac_lawyer');}
 private static function post_types($terms){$out=array();foreach(get_post_types(array('public'=>true),'objects') as $pt=>$obj){$hay=strtolower($pt.' '.$obj->label.' '.$obj->name);foreach($terms as $term){if(strpos($hay,strtolower($term))!==false){$out[]=$pt;break;}}}return array_values(array_unique($out));}
 private static function count_posts($types,$status='publish'){$types=$types?:array('post');$q=new WP_Query(array('post_type'=>$types,'post_status'=>$status,'posts_per_page'=>1,'fields'=>'ids','no_found_rows'=>false));return (int)$q->found_posts;}
 private static function recent($types,$limit=5){if(!$types)return array();$q=new WP_Query(array('post_type'=>$types,'post_status'=>'publish','posts_per_page'=>$limit,'orderby'=>'modified','order'=>'DESC'));$rows=array();foreach($q->posts as $p)$rows[]=array('id'=>$p->ID,'title'=>get_the_title($p),'date'=>get_the_modified_date('d M Y',$p),'url'=>get_permalink($p));return $rows;}
 public static function snapshot(){
  $matter=self::post_types(array('matter','perkara','case'));$request=self::post_types(array('request','legal request','permintaan'));$client=self::post_types(array('client','klien'));$retainer=self::post_types(array('retainer'));$task=self::post_types(array('task','tugas'));
  $data=array('matters'=>self::count_posts($matter),'requests'=>self::count_posts($request),'clients'=>self::count_posts($client),'retainers'=>self::count_posts($retainer),'tasks'=>self::count_posts($task),'recent_matters'=>self::recent($matter),'recent_requests'=>self::recent($request));
  return apply_filters('aclm_v712_dashboard_snapshot',$data);
 }
 public static function shortcode(){if(!self::allowed())return '<p>Akses dashboard ditolak.</p>'; $d=self::snapshot();ob_start();?><div class="aclm-v712" style="max-width:1400px;margin:32px auto;padding:0 22px;font-family:Inter,system-ui,sans-serif"><div style="background:#0d1b2a;color:#fff;border-radius:24px;padding:34px 38px;margin-bottom:22px"><div style="font-size:12px;letter-spacing:.14em;text-transform:uppercase;opacity:.7">ARKANA CIVIEL • LIVE MANAGEMENT</div><h1 style="font-size:36px;margin:10px 0 6px">Executive Command Center</h1><p style="margin:0;opacity:.78">Live operational snapshot from the WordPress management data layer.</p></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px;margin-bottom:22px"><?php foreach(array('matters'=>'Active Matters','requests'=>'Legal Requests','clients'=>'Clients','retainers'=>'Retainers','tasks'=>'Open Tasks') as $k=>$label):?><div style="background:#fff;border:1px solid #e7e9ee;border-radius:18px;padding:22px;box-shadow:0 8px 25px rgba(13,27,42,.06)"><div style="font-size:12px;color:#6b7280;text-transform:uppercase;letter-spacing:.08em"><?php echo esc_html($label);?></div><div style="font-size:34px;font-weight:750;margin-top:8px;color:#0d1b2a"><?php echo esc_html($d[$k]);?></div></div><?php endforeach;?></div><div style="display:grid;grid-template-columns:1.25fr 1fr;gap:18px"><section style="background:#fff;border:1px solid #e7e9ee;border-radius:20px;padding:24px"><h2 style="margin-top:0">Matter Workspace</h2><?php if($d['recent_matters']):?><div><?php foreach($d['recent_matters'] as $r):?><div style="padding:14px 0;border-bottom:1px solid #eef0f3"><a href="<?php echo esc_url($r['url']);?>" style="font-weight:650;color:#0d1b2a;text-decoration:none"><?php echo esc_html($r['title']);?></a><div style="font-size:12px;color:#7b8491;margin-top:4px">Updated <?php echo esc_html($r['date']);?></div></div><?php endforeach;?></div><?php else:?><p style="color:#6b7280">No live Matter records detected yet. Connect the Matter data source using the <code>aclm_v712_dashboard_snapshot</code> filter.</p><?php endif;?></section><section style="background:#0d1b2a;color:#fff;border-radius:20px;padding:24px"><div style="font-size:12px;letter-spacing:.1em;text-transform:uppercase;opacity:.65">AI MANAGEMENT COPILOT</div><h2>What needs attention?</h2><p style="opacity:.75">AI actions remain subject to V7.9 guardrails and V7.10 release gates.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><span style="padding:9px 12px;border:1px solid rgba(255,255,255,.18);border-radius:999px">Deadline risks</span><span style="padding:9px 12px;border:1px solid rgba(255,255,255,.18);border-radius:999px">Workload</span><span style="padding:9px 12px;border:1px solid rgba(255,255,255,.18);border-radius:999px">Client follow-up</span></div></section></div></div><?php return ob_get_clean();}
}
ACLM_V712_Live_Management_Dashboard::init();
}
