<?php
/** V7.17 Deadline, SLA & Calendar Intelligence foundation. Read-only operational signals. */
defined('ABSPATH') || exit;
if(!class_exists('ACLM_V717_Deadline_SLA_Calendar_Intelligence')){
final class ACLM_V717_Deadline_SLA_Calendar_Intelligence {
 public static function init(){add_shortcode('arkana_deadline_intelligence',array(__CLASS__,'shortcode'));}
 private static function allowed(){if(!class_exists('ACLM_V70_AI_Agent_Core')||!ACLM_V70_AI_Agent_Core::can_use())return false;$u=wp_get_current_user();return current_user_can('manage_options')||array_intersect(array('ac_managing_partner','ac_partner','ac_lawyer'),(array)$u->roles);}
 public static function snapshot(){if(!self::allowed())return array();$s=array('total'=>0,'critical'=>0,'warning'=>0,'upcoming'=>0,'overdue'=>0,'events'=>array(),'timezone'=>wp_timezone_string());$types=array('ac_deadline','ac_task','ac_hearing','ac_legal_request');foreach($types as $type){if(!post_type_exists($type))continue;$posts=get_posts(array('post_type'=>$type,'post_status'=>'publish','posts_per_page'=>100,'orderby'=>'date','order'=>'ASC'));foreach($posts as $p){$raw=get_post_meta($p->ID,'_aclm_due_at',true);if(!$raw)$raw=get_post_meta($p->ID,'_aclm_deadline',true);if(!$raw)continue;$ts=strtotime($raw);if(!$ts)continue;$s['total']++;$days=($ts-current_time('timestamp'))/DAY_IN_SECONDS;if($days<0)$s['overdue']++;elseif($days<=1)$s['critical']++;elseif($days<=7)$s['warning']++;else $s['upcoming']++;$s['events'][]=array('id'=>(int)$p->ID,'type'=>$type,'title'=>get_the_title($p->ID),'due'=>$raw,'days'=>(int)ceil($days));}}usort($s['events'],function($a,$b){return strcmp($a['due'],$b['due']);});$s['events']=array_slice($s['events'],0,20);return apply_filters('aclm_v717_deadline_snapshot',$s);}
 public static function create_run($prompt,$context=array()){if(!self::allowed()||!class_exists('ACLM_V70_AI_Agent_Core'))return 0;$context['assistant']='deadline_sla_calendar';$context['deadline_snapshot']=self::snapshot();return ACLM_V70_AI_Agent_Core::create_run($prompt,$context);}
 public static function shortcode(){if(!self::allowed())return '<p>Akses Deadline Intelligence ditolak.</p>';$s=self::snapshot();ob_start();?><section class="aclm-v717-deadlines" style="max-width:1100px;margin:40px auto;padding:0 20px"><h1>Deadline, SLA &amp; Calendar Intelligence</h1><p>Read-only operational deadline signals. This module does not reschedule, close, or modify records.</p><div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px"><div><strong><?php echo esc_html($s['overdue']);?></strong><br>Overdue</div><div><strong><?php echo esc_html($s['critical']);?></strong><br>Critical</div><div><strong><?php echo esc_html($s['warning']);?></strong><br>7-Day Warning</div><div><strong><?php echo esc_html($s['upcoming']);?></strong><br>Upcoming</div></div><h2>Priority Calendar</h2><ul><?php foreach($s['events'] as $e):?><li><strong><?php echo esc_html($e['title']);?></strong> — <?php echo esc_html($e['due']);?> (<?php echo esc_html($e['days']);?> days)</li><?php endforeach;?></ul></section><?php return ob_get_clean();}
}
ACLM_V717_Deadline_SLA_Calendar_Intelligence::init();
}
